name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[vars]
BASE_URL = "https://news.kenneth1203.dpdns.org/"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow"
database_id = "20bb6ce7-3ecb-4e9f-946d-b94d4141f7dd"
